name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add wasm32-unknown-unknown target
      run: rustup target add wasm32-unknown-unknown

    - name: Install dependencies
      run: make

    - name: Install dependencies fr this time
      run: make all

    - name: Upload v86 build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: v86-build
        path: ./
